<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents analysis of banned topics in a comment.
 */
class BannedTopicsResult {

    /**
     * Explanation of the banned topics analysis
     */
    public string $reasoning;

    /**
     * List of banned topics detected
     */
    public array $bannedTopics;

    /**
     * Proportion of comment discussing banned topics
     * Constraints: ge=0.0, le=1.0
     */
    public float $quantityOnBannedTopics;

    /**
     * Confidence level of banned topics detection
     * Constraints: ge=0.0, le=1.0
     */
    public float $confidence;

    /**
     * BannedTopicsResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->reasoning = $data['reasoning'] ?? '';
        $this->bannedTopics = $data['banned_topics'] ?? [];
        $this->quantityOnBannedTopics = floatval($data['quantity_on_banned_topics'] ?? 0.0);
        $this->confidence = floatval($data['confidence'] ?? 0.0);
    }
}
