<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the result of comment relevance analysis.
 */
class CommentRelevanceResult {

    /**
     * On-topic analysis result
     */
    public OnTopicResult $onTopic;

    /**
     * Banned topics analysis result
     */
    public BannedTopicsResult $bannedTopics;

    /**
     * CommentRelevanceResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->onTopic = new OnTopicResult($data['on_topic']);
        $this->bannedTopics = new BannedTopicsResult($data['banned_topics']);
    }
}
