<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the comprehensive evaluation of a comment's quality and toxicity.
 */
class CommentScore {

    /**
     * List of logical fallacies found
     */
    public array $logicalFallacies;

    /**
     * List of objectionable phrases found
     */
    public array $objectionablePhrases;

    /**
     * List of phrases with negative tone
     */
    public array $negativeTonePhrases;

    /**
     * Whether the comment appears to be low effort
     */
    public bool $appearsLowEffort;

    /**
     * Overall quality score (1=poor, 5=excellent)
     * Constraints: ge=1, le=5
     */
    public int $overallScore;

    /**
     * Toxicity score (0.0=not toxic, 1.0=highly toxic)
     * Constraints: ge=0.0, le=1.0
     */
    public float $toxicityScore;

    /**
     * Educational explanation of toxicity issues found
     */
    public string $toxicityExplanation;

    /**
     * CommentScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->logicalFallacies = array_map(fn($item) => new LogicalFallacy($item), $data['logical_fallacies'] ?? []);
        $this->objectionablePhrases = array_map(fn($item) => new ObjectionablePhrase($item), $data['objectionable_phrases'] ?? []);
        $this->negativeTonePhrases = array_map(fn($item) => new NegativeTonePhrase($item), $data['negative_tone_phrases'] ?? []);
        $this->appearsLowEffort = $data['appears_low_effort'] ?? false;
        $this->overallScore = $data['overall_score'] ?? 0;
        $this->toxicityScore = floatval($data['toxicity_score'] ?? 0.0);
        $this->toxicityExplanation = $data['toxicity_explanation'] ?? '';
    }
}
