<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents detailed information about detected dogwhistles.
 */
class DogwhistleDetails {

    /**
     * Specific dogwhistle terms detected
     */
    public array $dogwhistleTerms;

    /**
     * Categories of dogwhistles detected
     */
    public array $categories;

    /**
     * How subtle the dogwhistles are
     * Constraints: ge=0.0, le=1.0
     */
    public float $subtletyLevel;

    /**
     * Potential harm level of the dogwhistles
     * Constraints: ge=0.0, le=1.0
     */
    public float $harmPotential;

    /**
     * DogwhistleDetails constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->dogwhistleTerms = $data['dogwhistle_terms'] ?? [];
        $this->categories = $data['categories'] ?? [];
        $this->subtletyLevel = floatval($data['subtlety_level'] ?? 0.0);
        $this->harmPotential = floatval($data['harm_potential'] ?? 0.0);
    }
}
