<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the detection aspect of dogwhistle analysis.
 */
class DogwhistleDetection {

    /**
     * Explanation of the dogwhistle analysis
     */
    public string $reasoning;

    /**
     * Whether dogwhistles were detected
     */
    public bool $dogwhistlesDetected;

    /**
     * Confidence in the verdict (0.0=uncertain, 1.0=certain the verdict is correct)
     * Constraints: ge=0.0, le=1.0
     */
    public float $confidence;

    /**
     * DogwhistleDetection constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->reasoning = $data['reasoning'] ?? '';
        $this->dogwhistlesDetected = $data['dogwhistles_detected'] ?? false;
        $this->confidence = floatval($data['confidence'] ?? 0.0);
    }
}
