<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the result of dogwhistle detection analysis.
 */
class DogwhistleResult {

    /**
     * Dogwhistle detection analysis
     */
    public DogwhistleDetection $detection;

    /**
     * Optional detailed information about detected dogwhistles
     */
    public ?DogwhistleDetails $details;

    /**
     * DogwhistleResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->detection = new DogwhistleDetection($data['detection']);
        $this->details = isset($data['details']) ? new DogwhistleDetails($data['details']) : null;
    }
}
