<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Response from submitting feedback/score corrections.
 */
class FeedbackResponse {

    /**
     * 'ok' if feedback was recorded successfully
     */
    public string $status;

    /**
     * Human-readable confirmation message
     */
    public string $message;

    /**
     * FeedbackResponse constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->status = $data['status'] ?? '';
        $this->message = $data['message'] ?? '';
    }
}
