<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the response from initializing a topic.
 */
class InitTopicResponse {

    /**
     * UUID of the initialized article/topic
     */
    public string $articleId;

    /**
     * InitTopicResponse constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->articleId = $data['article_id'] ?? '';
    }
}
