<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Result of LLM-likeness detection for a comment.
 */
class LlmDetectionResult {

    /**
     * Probability the text was generated by an LLM (0.0=human, 1.0=certainly LLM)
     * Constraints: ge=0.0, le=1.0
     */
    public float $llmLikelihood;

    /**
     * Confidence in the verdict
     * Constraints: ge=0.0, le=1.0
     */
    public float $confidence;

    /**
     * Specific signals that contributed to the score
     */
    public array $signalsDetected;

    /**
     * Explanation of the analysis
     */
    public string $reasoning;

    /**
     * LlmDetectionResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->llmLikelihood = floatval($data['llm_likelihood'] ?? 0.0);
        $this->confidence = floatval($data['confidence'] ?? 0.0);
        $this->signalsDetected = array_map(fn($item) => new LlmDetectionSignal($item), $data['signals_detected'] ?? []);
        $this->reasoning = $data['reasoning'] ?? '';
    }
}
