<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * A specific signal indicating LLM-generated text.
 */
class LlmDetectionSignal {

    /**
     * Category: 'word_frequency', 'structural', 'stylistic', 'epistemic'
     */
    public string $signalType;

    /**
     * What was detected
     */
    public string $description;

    /**
     * The text that triggered this signal, if applicable
     */
    public string $quotedText;

    /**
     * LlmDetectionSignal constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->signalType = $data['signal_type'] ?? '';
        $this->description = $data['description'] ?? '';
        $this->quotedText = $data['quoted_text'] ?? '';
    }
}
