<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents a logical fallacy identified in a comment.
 */
class LogicalFallacy {

    /**
     * The name of the logical fallacy, e.g., 'straw man'
     */
    public string $fallacyName;

    /**
     * The part of the comment that contains the logical fallacy
     */
    public string $quotedLogicalFallacyExample;

    /**
     * Explanation of the fallacy and suggestions for improvement
     */
    public string $explanation;

    /**
     * Suggested rewrite (only provided when comment appears good-faith; otherwise empty)
     */
    public string $suggestedRewrite;

    /**
     * LogicalFallacy constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->fallacyName = $data['fallacy_name'] ?? '';
        $this->quotedLogicalFallacyExample = $data['quoted_logical_fallacy_example'] ?? '';
        $this->explanation = $data['explanation'] ?? '';
        $this->suggestedRewrite = $data['suggested_rewrite'] ?? '';
    }
}
