<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the result of a mega call containing multiple analysis types.
 */
class MegaCallResult {

    /**
     * Comment score result. Null unless requested via include_comment_score (Python) or 'commentscore' service (PHP).
     */
    public ?CommentScore $commentScore;

    /**
     * Spam detection result. Null unless requested via include_spam (Python) or 'spam' service (PHP).
     */
    public ?SpamDetectionResult $spamCheck;

    /**
     * Comment relevance result. Null unless requested via include_relevance (Python) or 'relevance' service (PHP).
     */
    public ?CommentRelevanceResult $relevanceCheck;

    /**
     * Dogwhistle detection result. Null unless requested via include_dogwhistle (Python) or 'dogwhistle' service (PHP).
     */
    public ?DogwhistleResult $dogwhistleCheck;

    /**
     * MegaCallResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->commentScore = isset($data['comment_score']) ? new CommentScore($data['comment_score']) : null;
        $this->spamCheck = isset($data['spam_check']) ? new SpamDetectionResult($data['spam_check']) : null;
        $this->relevanceCheck = isset($data['relevance_check']) ? new CommentRelevanceResult($data['relevance_check']) : null;
        $this->dogwhistleCheck = isset($data['dogwhistle_check']) ? new DogwhistleResult($data['dogwhistle_check']) : null;
    }
}
