<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents a phrase with negative tone identified in a comment.
 */
class NegativeTonePhrase {

    /**
     * The phrase with negative tone
     */
    public string $quotedNegativeTonePhrase;

    /**
     * Explanation of the negative tone
     */
    public string $explanation;

    /**
     * Suggested rewrite with more positive tone
     */
    public string $suggestedRewrite;

    /**
     * NegativeTonePhrase constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->quotedNegativeTonePhrase = $data['quoted_negative_tone_phrase'] ?? '';
        $this->explanation = $data['explanation'] ?? '';
        $this->suggestedRewrite = $data['suggested_rewrite'] ?? '';
    }
}
