<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents an objectionable phrase identified in a comment.
 */
class ObjectionablePhrase {

    /**
     * The objectionable phrase found in the comment
     */
    public string $quotedObjectionablePhrase;

    /**
     * Explanation of why this phrase is objectionable
     */
    public string $explanation;

    /**
     * Suggested rewrite of the objectionable content
     */
    public string $suggestedRewrite;

    /**
     * ObjectionablePhrase constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->quotedObjectionablePhrase = $data['quoted_objectionable_phrase'] ?? '';
        $this->explanation = $data['explanation'] ?? '';
        $this->suggestedRewrite = $data['suggested_rewrite'] ?? '';
    }
}
