<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents whether a comment is on-topic.
 */
class OnTopicResult {

    /**
     * Explanation of the relevance analysis
     */
    public string $reasoning;

    /**
     * Whether the comment is on-topic
     */
    public bool $onTopic;

    /**
     * Confidence level (0.0=low, 1.0=high)
     * Constraints: ge=0.0, le=1.0
     */
    public float $confidence;

    /**
     * OnTopicResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->reasoning = $data['reasoning'] ?? '';
        $this->onTopic = $data['on_topic'] ?? false;
        $this->confidence = floatval($data['confidence'] ?? 0.0);
    }
}
