<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Perspective-compatible comment analysis result.
Scores represent the probability (0.0-1.0) that a reader would perceive
the comment as having each attribute. Compatible with Google's Perspective API
response format for easy migration.
 */
class PerspectiveResult {

    /**
     * Rude, disrespectful, or unreasonable content likely to make people leave a discussion
     */
    public PerspectiveAttributeScore $toxicity;

    /**
     * Very hateful, aggressive, or disrespectful content; higher threshold than toxicity
     */
    public PerspectiveAttributeScore $severeToxicity;

    /**
     * Negative or hateful content targeting someone because of their identity
     */
    public PerspectiveAttributeScore $identityAttack;

    /**
     * Insulting, inflammatory, or negative comment towards a person or group
     */
    public PerspectiveAttributeScore $insult;

    /**
     * Swear words, curse words, or other obscene language
     */
    public PerspectiveAttributeScore $profanity;

    /**
     * Intention to inflict pain, injury, or violence
     */
    public PerspectiveAttributeScore $threat;

    /**
     * References to sexual acts or body parts in sexual context
     */
    public PerspectiveAttributeScore $sexuallyExplicit;

    /**
     * Difficult to understand, nonsensical, or poorly written
     */
    public PerspectiveAttributeScore $incoherent;

    /**
     * Intended to provoke or inflame rather than discuss
     */
    public PerspectiveAttributeScore $inflammatory;

    /**
     * Irrelevant, promotional, or nonsensical content
     */
    public PerspectiveAttributeScore $spam;

    /**
     * Demonstrates logical reasoning or evidence-based arguments
     */
    public PerspectiveAttributeScore $reasoning;

    /**
     * Shows genuine curiosity, asks thoughtful questions
     */
    public PerspectiveAttributeScore $curiosity;

    /**
     * Demonstrates nuanced thinking, acknowledges complexity
     */
    public PerspectiveAttributeScore $nuance;

    /**
     * Shows empathy, understanding, or concern for others
     */
    public PerspectiveAttributeScore $compassion;

    /**
     * Contributes constructively, adds to the conversation
     */
    public PerspectiveAttributeScore $constructiveness;

    /**
     * Treats others and their views with dignity
     */
    public PerspectiveAttributeScore $respect;

    /**
     * One-sentence plain-language summary of the comment's character
     */
    public string $summary;

    /**
     * PerspectiveResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->toxicity = new PerspectiveAttributeScore($data['toxicity']);
        $this->severeToxicity = new PerspectiveAttributeScore($data['severe_toxicity']);
        $this->identityAttack = new PerspectiveAttributeScore($data['identity_attack']);
        $this->insult = new PerspectiveAttributeScore($data['insult']);
        $this->profanity = new PerspectiveAttributeScore($data['profanity']);
        $this->threat = new PerspectiveAttributeScore($data['threat']);
        $this->sexuallyExplicit = new PerspectiveAttributeScore($data['sexually_explicit']);
        $this->incoherent = new PerspectiveAttributeScore($data['incoherent']);
        $this->inflammatory = new PerspectiveAttributeScore($data['inflammatory']);
        $this->spam = new PerspectiveAttributeScore($data['spam']);
        $this->reasoning = new PerspectiveAttributeScore($data['reasoning']);
        $this->curiosity = new PerspectiveAttributeScore($data['curiosity']);
        $this->nuance = new PerspectiveAttributeScore($data['nuance']);
        $this->compassion = new PerspectiveAttributeScore($data['compassion']);
        $this->constructiveness = new PerspectiveAttributeScore($data['constructiveness']);
        $this->respect = new PerspectiveAttributeScore($data['respect']);
        $this->summary = $data['summary'] ?? '';
    }
}
