<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Google-style score object used in Perspective compatibility responses.
 */
class PerspectiveScore {

    /**
     * Probability-style score between 0.0 and 1.0. Higher numbers mean more of the requested attribute.
     * Constraints: ge=0.0, le=1.0
     */
    public float $value;

    /**
     * Score type. Respectify currently returns `PROBABILITY`, meaning the value is a 0 to 1 probability-style score.
     */
    public string $type;

    /**
     * PerspectiveScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->value = floatval($data['value'] ?? 0.0);
        $this->type = $data['type'] ?? '';
    }
}
