<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Internal schema for LLM output before span resolution.
The LLM returns quoted_text for spans; Python code then resolves to character positions.
 */
class PerspectiveRawScores {

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $toxicity;

    /**
     * Quoted text from the comment most relevant to toxicity
     */
    public string $toxicitySpan;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $severeToxicity;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $identityAttack;

    /**
     * Quoted text for identity attack
     */
    public string $identityAttackSpan;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $insult;

    /**
     * Quoted text for insult
     */
    public string $insultSpan;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $profanity;

    /**
     * Quoted text for profanity
     */
    public string $profanitySpan;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $threat;

    /**
     * Quoted text for threat
     */
    public string $threatSpan;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $sexuallyExplicit;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $incoherent;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $inflammatory;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $spam;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $reasoning;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $curiosity;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $nuance;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $compassion;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $constructiveness;

    /**
     * 
     * Constraints: ge=0.0, le=1.0
     */
    public float $respect;

    /**
     * One-sentence summary
     */
    public string $summary;

    /**
     * PerspectiveRawScores constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->toxicity = floatval($data['toxicity'] ?? 0.0);
        $this->toxicitySpan = $data['toxicity_span'] ?? '';
        $this->severeToxicity = floatval($data['severe_toxicity'] ?? 0.0);
        $this->identityAttack = floatval($data['identity_attack'] ?? 0.0);
        $this->identityAttackSpan = $data['identity_attack_span'] ?? '';
        $this->insult = floatval($data['insult'] ?? 0.0);
        $this->insultSpan = $data['insult_span'] ?? '';
        $this->profanity = floatval($data['profanity'] ?? 0.0);
        $this->profanitySpan = $data['profanity_span'] ?? '';
        $this->threat = floatval($data['threat'] ?? 0.0);
        $this->threatSpan = $data['threat_span'] ?? '';
        $this->sexuallyExplicit = floatval($data['sexually_explicit'] ?? 0.0);
        $this->incoherent = floatval($data['incoherent'] ?? 0.0);
        $this->inflammatory = floatval($data['inflammatory'] ?? 0.0);
        $this->spam = floatval($data['spam'] ?? 0.0);
        $this->reasoning = floatval($data['reasoning'] ?? 0.0);
        $this->curiosity = floatval($data['curiosity'] ?? 0.0);
        $this->nuance = floatval($data['nuance'] ?? 0.0);
        $this->compassion = floatval($data['compassion'] ?? 0.0);
        $this->constructiveness = floatval($data['constructiveness'] ?? 0.0);
        $this->respect = floatval($data['respect'] ?? 0.0);
        $this->summary = $data['summary'] ?? '';
    }
}
