<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Google-style span score for a specific part of the comment.
 */
class PerspectiveAnalyzeCommentSpanScore {

    /**
     * Start offset for the span in UTF-16 code units
     * Constraints: ge=0
     */
    public int $begin;

    /**
     * End offset for the span in UTF-16 code units
     * Constraints: ge=0
     */
    public int $end;

    /**
     * Score for this specific span
     */
    public PerspectiveScore $score;

    /**
     * PerspectiveAnalyzeCommentSpanScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->begin = $data['begin'] ?? 0;
        $this->end = $data['end'] ?? 0;
        $this->score = new PerspectiveScore($data['score']);
    }
}
