<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Response returned by Respectify's public Perspective-compatible suggestscore endpoint.
 */
class PerspectiveSuggestCommentScoreResponse {

    /**
     * Echoed requested languages when the caller supplied them
     */
    public ?array $requestedLanguages;

    /**
     * Opaque caller token echoed back when supplied
     */
    public ?string $clientToken;

    /**
     * PerspectiveSuggestCommentScoreResponse constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->requestedLanguages = $data['requestedLanguages'] ?? null;
        $this->clientToken = $data['clientToken'] ?? null;
    }
}
