<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Response returned by Respectify's public Perspective-compatible analyse endpoint.
 */
class PerspectiveAnalyzeCommentResponse {

    /**
     * Map of requested Perspective attribute names, such as `TOXICITY` or `INSULT`, to their score objects. Each value contains a `summaryScore` and, when requested, optional `spanScores`.
     */
    public array $attributeScores;

    /**
     * Requested or effective language context for this response, as language codes such as `en`, `es`, or `fr`.
     */
    public array $languages;

    /**
     * Present only if Respectify actually detected languages, as language codes such as `en`, `es`, or `fr`.
     */
    public ?array $detectedLanguages;

    /**
     * Caller-provided correlation token, echoed back unchanged when supplied. Use this if you want to match the response to your own request ID.
     */
    public ?string $clientToken;

    /**
     * PerspectiveAnalyzeCommentResponse constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->attributeScores = [];
        foreach (($data['attributeScores'] ?? []) as $key => $item) {
            $this->attributeScores[$key] = new PerspectiveAnalyzeCommentAttributeScore($item);
        }
        $this->languages = $data['languages'] ?? [];
        $this->detectedLanguages = $data['detectedLanguages'] ?? null;
        $this->clientToken = $data['clientToken'] ?? null;
    }
}
