<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Google-style attribute score entry returned by analyzeComment.
 */
class PerspectiveAnalyzeCommentAttributeScore {

    /**
     * Overall score for the attribute. This is the main score most integrations use for thresholds and moderation decisions.
     */
    public PerspectiveScore $summaryScore;

    /**
     * Optional scores for specific spans of text that contributed to the attribute. Returned only when span annotations were requested.
     */
    public ?array $spanScores;

    /**
     * PerspectiveAnalyzeCommentAttributeScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->summaryScore = new PerspectiveScore($data['summaryScore']);
        $this->spanScores = isset($data['spanScores']) ? array_map(fn($item) => new PerspectiveAnalyzeCommentSpanScore($item), $data['spanScores']) : null;
    }
}
