<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Score for a single Perspective attribute, with optional span-level detail.
 */
class PerspectiveAttributeScore {

    /**
     * Summary score (0.0-1.0 probability)
     * Constraints: ge=0.0, le=1.0
     */
    public float $score;

    /**
     * Per-span scores identifying which parts of the comment triggered this attribute
     */
    public array $spanScores;

    /**
     * PerspectiveAttributeScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->score = floatval($data['score'] ?? 0.0);
        $this->spanScores = array_map(fn($item) => new PerspectiveSpanScore($item), $data['span_scores'] ?? []);
    }
}
