<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * A score for a specific span of text within the comment.
 */
class PerspectiveSpanScore {

    /**
     * Start character position in the original comment
     * Constraints: ge=0
     */
    public int $begin;

    /**
     * End character position in the original comment
     * Constraints: ge=0
     */
    public int $end;

    /**
     * Score for this span (0.0-1.0)
     * Constraints: ge=0.0, le=1.0
     */
    public float $score;

    /**
     * The quoted text from the comment for this span
     */
    public string $quotedText;

    /**
     * PerspectiveSpanScore constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->begin = $data['begin'] ?? 0;
        $this->end = $data['end'] ?? 0;
        $this->score = floatval($data['score'] ?? 0.0);
        $this->quotedText = $data['quoted_text'] ?? '';
    }
}
