<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the result of spam detection analysis.
 */
class SpamDetectionResult {

    /**
     * Explanation of the spam analysis
     */
    public string $reasoning;

    /**
     * Whether the comment is detected as spam
     */
    public bool $isSpam;

    /**
     * Confidence level (0.0=low, 1.0=high)
     * Constraints: ge=0.0, le=1.0
     */
    public float $confidence;

    /**
     * SpamDetectionResult constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->reasoning = $data['reasoning'] ?? '';
        $this->isSpam = $data['is_spam'] ?? false;
        $this->confidence = floatval($data['confidence'] ?? 0.0);
    }
}
