<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Represents the response from checking user credentials.
 */
class UserCheckResponse {

    /**
     * Success status as string
     */
    public ?string $success;

    /**
     * Information message about the check
     */
    public ?string $info;

    /**
     * User subscription information
     */
    public ?UserSubscriptionStatus $subscription;

    /**
     * Error title when subscription required
     */
    public ?string $title;

    /**
     * Error description when subscription required
     */
    public ?string $description;

    /**
     * UserCheckResponse constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->success = $data['success'] ?? null;
        $this->info = $data['info'] ?? null;
        $this->subscription = isset($data['subscription']) ? new UserSubscriptionStatus($data['subscription']) : null;
        $this->title = $data['title'] ?? null;
        $this->description = $data['description'] ?? null;
    }
}
