<?php

/*
 * ===============================================================================
 * WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * ===============================================================================
 * 
 * This file is automatically generated from Python schemas in:
 * respectify-python/respectify/schemas.py
 * 
 * To make changes:
 * 1. Edit the Python schema file
 * 2. Run: python schema_generator.py
 * 3. All PHP classes and documentation will be regenerated
 * 
 * Any manual edits to this file WILL BE OVERWRITTEN!
 * ===============================================================================
 */

namespace Respectify\Schemas;

/**
 * Information about a user's subscription status.
 */
class UserSubscriptionStatus {

    /**
     * Whether the subscription is active
     */
    public bool $active;

    /**
     * Current subscription status
     */
    public ?string $status;

    /**
     * Subscription expiration date
     */
    public ?string $expires;

    /**
     * Name of the subscription plan (e.g., 'Personal', 'Professional', 'Anti-Spam Only')
     */
    public ?string $planName;

    /**
     * List of API endpoints allowed for this plan (e.g., ['antispam', 'commentscore'])
     */
    public array $allowedEndpoints;

    /**
     * Error message if any
     */
    public ?string $error;

    /**
     * UserSubscriptionStatus constructor.
     * @param array $data The JSON data from the API
     */
    public function __construct(array $data) {
        $this->active = $data['active'] ?? false;
        $this->status = $data['status'] ?? null;
        $this->expires = $data['expires'] ?? null;
        $this->planName = $data['plan_name'] ?? null;
        $this->allowedEndpoints = $data['allowed_endpoints'] ?? [];
        $this->error = $data['error'] ?? null;
    }
}
